name: Testing

on:
  push:
    branches:
      - 'released'
    tags:
      - '!v*'
  pull_request:
    branches:
      - 'released'

jobs:
  # ***********
  # RUST - linting
  # ***********
  lint-rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Check formatting
        working-directory: ./rust
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Annotate commit with clippy warnings
        working-directory: ./rust
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Security audit
        working-directory: ./rust
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # ***********
  # RUST - testing
  # ***********
  test-rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Tests
        working-directory: ./rust
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast

  # ***********
  # NODEJS - testing
  # ***********
  test-nodejs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Get yarn cache
        working-directory: ./nodejs
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        working-directory: ./nodejs
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Node version
        working-directory: ./nodejs
        run: node --version

      - name: npm version
        working-directory: ./nodejs
        run: npm --version

      - name: Yarn version
        working-directory: ./nodejs
        run: yarn --version

      - name: Yarn install dependencies
        working-directory: ./nodejs
        run: yarn install --frozen-lockfile

      - name: Yarn test
        working-directory: ./nodejs
        run: yarn test
